### ISSUE TITLE
Ask for tha data in `PROJECTS_DIR`

### ISSUE THREAD

**Issue by itaowei** [shangqing-liu/ATOM#1]
Thanks for your wonderful work!
May I ask for the raw data which stored in `PROJECTS_DIR` ("/home/shangqing/Downloads/project/java-project" in `gitproject.py`)
When I try to preprocess the data, I find it went wrong because of the lack of that data.
I had already downloaded other data from https://zenodo.org/record/4066398#.X32LSZMzZTZ

Looking forward to your reply!

Thanks a lot!

**Comment by shangqing-liu** [comment]
Hi, thanks for paying attention to our work. I cloned 56 projects on the local machines, due to the size of the projects, I cannot upload them, but you can clone the repos by yourself.

**Comment by itaowei** [comment]
> Hi, thanks for paying attention to our work. I cloned 56 projects on the local machines, due to the size of the projects, I cannot upload them, but you can clone the repos by yourself.

Thanks for your reply!
May I ask what versions you downloaded from them? 
In the folder `PROJECTS_DIR`, do you download them just through the `git clone https://...... .git`?
I am sad that this excellent project cannot be fully run because of the lack of these data.

Have a nice day!

**Comment by shangqing-liu** [comment]
Yes, I download the projects by git clone.
