### ISSUE TITLE
DIFF NULL

### ISSUE THREAD

**Issue by brunaostii** [shangqing-liu/ATOM#2]
Hi, Thanks for your wonderful work!
Well, the code reads everything about the git project but the diff, so i checked the code and discover that the parser is throwing exceptions about all commits, as a result the csv file output is blank. So, I tested the same projects that are available for download in your examples, and the output continues blank. Do you know what I can be doing wrong?

Thanks for your time!

**Comment by shangqing-liu** [comment]
Sorry, I cannot understand your problem. Can you give me more details?

Thanks

**Comment by brunaostii** [comment]
The first code ins't generating the csv, the csv is saving null.

**Comment by shangqing-liu** [comment]
I suggest you double-check it since the code is correct and I have tested many times.

**Comment by brunaostii** [comment]
sorry, i don't mean the code is wrong. I was thinking if you maybe know what I was doing wrong to get this.
